//! # Generated Protocol Buffers Code
//!
//! This module contains the generated code from the protocol buffers definitions.
//! Do not edit this file directly as it is generated by the build script.

// Re-export the generated network service code
pub mod network {
    tonic::include_proto!("network");
}

// Re-export commonly used types for convenience
pub use network::{
    network_service_client::NetworkServiceClient,
    network_service_server::{NetworkService, NetworkServiceServer},
    ConnectContainerRequest, ConnectContainerResponse, CreateNetworkRequest,
    DeleteNetworkRequest, DisconnectContainerRequest, GetNetworkRequest,
    IsolationLevel, ListNetworksResponse, Network, NetworkDriverType, NetworkStats,
};